//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerUser.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomersTbl
    {
        [Key]
        public int CustomerID { get; set; }
        [DisplayName ("First Name")]
        public string FName { get; set; }
        [DisplayName ("Last Name")]
        public string LName { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z][a-zA-Z0-9]*[@][a-zA-Z]*[.][c][o][m]", ErrorMessage = "Invalid Email!")]
        public string Email { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        [Required]
        [MinLength(4, ErrorMessage = "Password must be 4 or more characters")]
        [DataType(DataType.Password)]
        [DisplayName ("Password")]
        public string Passcode { get; set; }
        [Compare("Passcode")]

        [DisplayName("Confirm Password")]
        public string ConfirmPasscode { get; set; }
    }
}
